#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSWorkFlow
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="xnvaufit_NganHang")]
	public partial class dbNganHangOnlineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertDiaChi(DiaChi instance);
    partial void UpdateDiaChi(DiaChi instance);
    partial void DeleteDiaChi(DiaChi instance);
    partial void InsertLoaiTaiKhoan(LoaiTaiKhoan instance);
    partial void UpdateLoaiTaiKhoan(LoaiTaiKhoan instance);
    partial void DeleteLoaiTaiKhoan(LoaiTaiKhoan instance);
    partial void InsertLoaiGiaoDich(LoaiGiaoDich instance);
    partial void UpdateLoaiGiaoDich(LoaiGiaoDich instance);
    partial void DeleteLoaiGiaoDich(LoaiGiaoDich instance);
    partial void InsertLichSuGiaoDich(LichSuGiaoDich instance);
    partial void UpdateLichSuGiaoDich(LichSuGiaoDich instance);
    partial void DeleteLichSuGiaoDich(LichSuGiaoDich instance);
    partial void InsertLoaiThe(LoaiThe instance);
    partial void UpdateLoaiThe(LoaiThe instance);
    partial void DeleteLoaiThe(LoaiThe instance);
    partial void InsertMoiGioi(MoiGioi instance);
    partial void UpdateMoiGioi(MoiGioi instance);
    partial void DeleteMoiGioi(MoiGioi instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertThamSo(ThamSo instance);
    partial void UpdateThamSo(ThamSo instance);
    partial void DeleteThamSo(ThamSo instance);
    partial void InsertThe(The instance);
    partial void UpdateThe(The instance);
    partial void DeleteThe(The instance);
    #endregion
		
		public dbNganHangOnlineDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["xnvaufit_NganHangConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangOnlineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangOnlineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangOnlineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangOnlineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DiaChi> DiaChis
		{
			get
			{
				return this.GetTable<DiaChi>();
			}
		}
		
		public System.Data.Linq.Table<LoaiTaiKhoan> LoaiTaiKhoans
		{
			get
			{
				return this.GetTable<LoaiTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<LoaiGiaoDich> LoaiGiaoDiches
		{
			get
			{
				return this.GetTable<LoaiGiaoDich>();
			}
		}
		
		public System.Data.Linq.Table<LichSuGiaoDich> LichSuGiaoDiches
		{
			get
			{
				return this.GetTable<LichSuGiaoDich>();
			}
		}
		
		public System.Data.Linq.Table<LoaiThe> LoaiThes
		{
			get
			{
				return this.GetTable<LoaiThe>();
			}
		}
		
		public System.Data.Linq.Table<MoiGioi> MoiGiois
		{
			get
			{
				return this.GetTable<MoiGioi>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<ThamSo> ThamSos
		{
			get
			{
				return this.GetTable<ThamSo>();
			}
		}
		
		public System.Data.Linq.Table<The> Thes
		{
			get
			{
				return this.GetTable<The>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaAdmin;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _Email;
		
		private System.Nullable<int> _TinhTrang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAdminChanging(string value);
    partial void OnMaAdminChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAdmin", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaAdmin
		{
			get
			{
				return this._MaAdmin;
			}
			set
			{
				if ((this._MaAdmin != value))
				{
					this.OnMaAdminChanging(value);
					this.SendPropertyChanging();
					this._MaAdmin = value;
					this.SendPropertyChanged("MaAdmin");
					this.OnMaAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _MaTaiKhoan;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private System.Nullable<int> _CMNDHoChieu;
		
		private System.Nullable<int> _TinhTrang;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnMaTaiKhoanChanging(string value);
    partial void OnMaTaiKhoanChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnCMNDHoChieuChanging(System.Nullable<int> value);
    partial void OnCMNDHoChieuChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public KhachHang()
		{
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoan", DbType="VarChar(10)")]
		public string MaTaiKhoan
		{
			get
			{
				return this._MaTaiKhoan;
			}
			set
			{
				if ((this._MaTaiKhoan != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoan = value;
					this.SendPropertyChanged("MaTaiKhoan");
					this.OnMaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMNDHoChieu", DbType="Int")]
		public System.Nullable<int> CMNDHoChieu
		{
			get
			{
				return this._CMNDHoChieu;
			}
			set
			{
				if ((this._CMNDHoChieu != value))
				{
					this.OnCMNDHoChieuChanging(value);
					this.SendPropertyChanging();
					this._CMNDHoChieu = value;
					this.SendPropertyChanged("CMNDHoChieu");
					this.OnCMNDHoChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_KhachHang", Storage="_TaiKhoan", ThisKey="MaTaiKhoan", OtherKey="MaTaiKhoan", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._MaTaiKhoan = value.MaTaiKhoan;
					}
					else
					{
						this._MaTaiKhoan = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaChi")]
	public partial class DiaChi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDiaChi;
		
		private string _MaTaiKhoan;
		
		private System.Nullable<int> _SoNha;
		
		private string _Duong;
		
		private string _PhuongXa;
		
		private string _QuanHuyen;
		
		private string _TinhThanh;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaChiChanging(string value);
    partial void OnMaDiaChiChanged();
    partial void OnMaTaiKhoanChanging(string value);
    partial void OnMaTaiKhoanChanged();
    partial void OnSoNhaChanging(System.Nullable<int> value);
    partial void OnSoNhaChanged();
    partial void OnDuongChanging(string value);
    partial void OnDuongChanged();
    partial void OnPhuongXaChanging(string value);
    partial void OnPhuongXaChanged();
    partial void OnQuanHuyenChanging(string value);
    partial void OnQuanHuyenChanged();
    partial void OnTinhThanhChanging(string value);
    partial void OnTinhThanhChanged();
    #endregion
		
		public DiaChi()
		{
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaChi", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDiaChi
		{
			get
			{
				return this._MaDiaChi;
			}
			set
			{
				if ((this._MaDiaChi != value))
				{
					this.OnMaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._MaDiaChi = value;
					this.SendPropertyChanged("MaDiaChi");
					this.OnMaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoan", DbType="VarChar(10)")]
		public string MaTaiKhoan
		{
			get
			{
				return this._MaTaiKhoan;
			}
			set
			{
				if ((this._MaTaiKhoan != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoan = value;
					this.SendPropertyChanged("MaTaiKhoan");
					this.OnMaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNha", DbType="Int")]
		public System.Nullable<int> SoNha
		{
			get
			{
				return this._SoNha;
			}
			set
			{
				if ((this._SoNha != value))
				{
					this.OnSoNhaChanging(value);
					this.SendPropertyChanging();
					this._SoNha = value;
					this.SendPropertyChanged("SoNha");
					this.OnSoNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duong", DbType="NVarChar(50)")]
		public string Duong
		{
			get
			{
				return this._Duong;
			}
			set
			{
				if ((this._Duong != value))
				{
					this.OnDuongChanging(value);
					this.SendPropertyChanging();
					this._Duong = value;
					this.SendPropertyChanged("Duong");
					this.OnDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongXa", DbType="NVarChar(50)")]
		public string PhuongXa
		{
			get
			{
				return this._PhuongXa;
			}
			set
			{
				if ((this._PhuongXa != value))
				{
					this.OnPhuongXaChanging(value);
					this.SendPropertyChanging();
					this._PhuongXa = value;
					this.SendPropertyChanged("PhuongXa");
					this.OnPhuongXaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanHuyen", DbType="NVarChar(50)")]
		public string QuanHuyen
		{
			get
			{
				return this._QuanHuyen;
			}
			set
			{
				if ((this._QuanHuyen != value))
				{
					this.OnQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._QuanHuyen = value;
					this.SendPropertyChanged("QuanHuyen");
					this.OnQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhThanh", DbType="NVarChar(50)")]
		public string TinhThanh
		{
			get
			{
				return this._TinhThanh;
			}
			set
			{
				if ((this._TinhThanh != value))
				{
					this.OnTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._TinhThanh = value;
					this.SendPropertyChanged("TinhThanh");
					this.OnTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_DiaChi", Storage="_TaiKhoan", ThisKey="MaTaiKhoan", OtherKey="MaTaiKhoan", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.DiaChis.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.DiaChis.Add(this);
						this._MaTaiKhoan = value.MaTaiKhoan;
					}
					else
					{
						this._MaTaiKhoan = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiTaiKhoan")]
	public partial class LoaiTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiTaiKhoan;
		
		private string _TenLoaiTaiKhoan;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiTaiKhoanChanging(string value);
    partial void OnMaLoaiTaiKhoanChanged();
    partial void OnTenLoaiTaiKhoanChanging(string value);
    partial void OnTenLoaiTaiKhoanChanged();
    #endregion
		
		public LoaiTaiKhoan()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTaiKhoan", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiTaiKhoan
		{
			get
			{
				return this._MaLoaiTaiKhoan;
			}
			set
			{
				if ((this._MaLoaiTaiKhoan != value))
				{
					this.OnMaLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTaiKhoan = value;
					this.SendPropertyChanged("MaLoaiTaiKhoan");
					this.OnMaLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiTaiKhoan", DbType="NVarChar(50)")]
		public string TenLoaiTaiKhoan
		{
			get
			{
				return this._TenLoaiTaiKhoan;
			}
			set
			{
				if ((this._TenLoaiTaiKhoan != value))
				{
					this.OnTenLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiTaiKhoan = value;
					this.SendPropertyChanged("TenLoaiTaiKhoan");
					this.OnTenLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTaiKhoan_TaiKhoan", Storage="_TaiKhoans", ThisKey="MaLoaiTaiKhoan", OtherKey="MaLoaiTaiKhoan")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTaiKhoan = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiGiaoDich")]
	public partial class LoaiGiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiGiaoDich;
		
		private string _TenLoaiGiaoDich;
		
		private EntitySet<LichSuGiaoDich> _LichSuGiaoDiches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiGiaoDichChanging(string value);
    partial void OnMaLoaiGiaoDichChanged();
    partial void OnTenLoaiGiaoDichChanging(string value);
    partial void OnTenLoaiGiaoDichChanged();
    #endregion
		
		public LoaiGiaoDich()
		{
			this._LichSuGiaoDiches = new EntitySet<LichSuGiaoDich>(new Action<LichSuGiaoDich>(this.attach_LichSuGiaoDiches), new Action<LichSuGiaoDich>(this.detach_LichSuGiaoDiches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGiaoDich", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiGiaoDich
		{
			get
			{
				return this._MaLoaiGiaoDich;
			}
			set
			{
				if ((this._MaLoaiGiaoDich != value))
				{
					this.OnMaLoaiGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGiaoDich = value;
					this.SendPropertyChanged("MaLoaiGiaoDich");
					this.OnMaLoaiGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiGiaoDich", DbType="NVarChar(50)")]
		public string TenLoaiGiaoDich
		{
			get
			{
				return this._TenLoaiGiaoDich;
			}
			set
			{
				if ((this._TenLoaiGiaoDich != value))
				{
					this.OnTenLoaiGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiGiaoDich = value;
					this.SendPropertyChanged("TenLoaiGiaoDich");
					this.OnTenLoaiGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiGiaoDich_LichSuGiaoDich", Storage="_LichSuGiaoDiches", ThisKey="MaLoaiGiaoDich", OtherKey="MaLoaiGiaoDich")]
		public EntitySet<LichSuGiaoDich> LichSuGiaoDiches
		{
			get
			{
				return this._LichSuGiaoDiches;
			}
			set
			{
				this._LichSuGiaoDiches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichSuGiaoDiches(LichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.LoaiGiaoDich = this;
		}
		
		private void detach_LichSuGiaoDiches(LichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.LoaiGiaoDich = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichSuGiaoDich")]
	public partial class LichSuGiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLichSuGiaoDich;
		
		private string _MaThe;
		
		private string _MaLoaiGiaoDich;
		
		private System.Nullable<int> _SoTheNhan;
		
		private System.Nullable<System.DateTime> _NgayGiaoDich;
		
		private System.Nullable<decimal> _SoTienGiaoDich;
		
		private System.Nullable<int> _TinhTrang;
		
		private EntityRef<LoaiGiaoDich> _LoaiGiaoDich;
		
		private EntityRef<The> _The;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLichSuGiaoDichChanging(string value);
    partial void OnMaLichSuGiaoDichChanged();
    partial void OnMaTheChanging(string value);
    partial void OnMaTheChanged();
    partial void OnMaLoaiGiaoDichChanging(string value);
    partial void OnMaLoaiGiaoDichChanged();
    partial void OnSoTheNhanChanging(System.Nullable<int> value);
    partial void OnSoTheNhanChanged();
    partial void OnNgayGiaoDichChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoDichChanged();
    partial void OnSoTienGiaoDichChanging(System.Nullable<decimal> value);
    partial void OnSoTienGiaoDichChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public LichSuGiaoDich()
		{
			this._LoaiGiaoDich = default(EntityRef<LoaiGiaoDich>);
			this._The = default(EntityRef<The>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLichSuGiaoDich", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLichSuGiaoDich
		{
			get
			{
				return this._MaLichSuGiaoDich;
			}
			set
			{
				if ((this._MaLichSuGiaoDich != value))
				{
					this.OnMaLichSuGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._MaLichSuGiaoDich = value;
					this.SendPropertyChanged("MaLichSuGiaoDich");
					this.OnMaLichSuGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThe", DbType="VarChar(10)")]
		public string MaThe
		{
			get
			{
				return this._MaThe;
			}
			set
			{
				if ((this._MaThe != value))
				{
					if (this._The.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTheChanging(value);
					this.SendPropertyChanging();
					this._MaThe = value;
					this.SendPropertyChanged("MaThe");
					this.OnMaTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGiaoDich", DbType="VarChar(10)")]
		public string MaLoaiGiaoDich
		{
			get
			{
				return this._MaLoaiGiaoDich;
			}
			set
			{
				if ((this._MaLoaiGiaoDich != value))
				{
					if (this._LoaiGiaoDich.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGiaoDich = value;
					this.SendPropertyChanged("MaLoaiGiaoDich");
					this.OnMaLoaiGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTheNhan", DbType="Int")]
		public System.Nullable<int> SoTheNhan
		{
			get
			{
				return this._SoTheNhan;
			}
			set
			{
				if ((this._SoTheNhan != value))
				{
					this.OnSoTheNhanChanging(value);
					this.SendPropertyChanging();
					this._SoTheNhan = value;
					this.SendPropertyChanged("SoTheNhan");
					this.OnSoTheNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoDich", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGiaoDich
		{
			get
			{
				return this._NgayGiaoDich;
			}
			set
			{
				if ((this._NgayGiaoDich != value))
				{
					this.OnNgayGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoDich = value;
					this.SendPropertyChanged("NgayGiaoDich");
					this.OnNgayGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienGiaoDich", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoTienGiaoDich
		{
			get
			{
				return this._SoTienGiaoDich;
			}
			set
			{
				if ((this._SoTienGiaoDich != value))
				{
					this.OnSoTienGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._SoTienGiaoDich = value;
					this.SendPropertyChanged("SoTienGiaoDich");
					this.OnSoTienGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiGiaoDich_LichSuGiaoDich", Storage="_LoaiGiaoDich", ThisKey="MaLoaiGiaoDich", OtherKey="MaLoaiGiaoDich", IsForeignKey=true)]
		public LoaiGiaoDich LoaiGiaoDich
		{
			get
			{
				return this._LoaiGiaoDich.Entity;
			}
			set
			{
				LoaiGiaoDich previousValue = this._LoaiGiaoDich.Entity;
				if (((previousValue != value) 
							|| (this._LoaiGiaoDich.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiGiaoDich.Entity = null;
						previousValue.LichSuGiaoDiches.Remove(this);
					}
					this._LoaiGiaoDich.Entity = value;
					if ((value != null))
					{
						value.LichSuGiaoDiches.Add(this);
						this._MaLoaiGiaoDich = value.MaLoaiGiaoDich;
					}
					else
					{
						this._MaLoaiGiaoDich = default(string);
					}
					this.SendPropertyChanged("LoaiGiaoDich");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="The_LichSuGiaoDich", Storage="_The", ThisKey="MaThe", OtherKey="MaThe", IsForeignKey=true)]
		public The The
		{
			get
			{
				return this._The.Entity;
			}
			set
			{
				The previousValue = this._The.Entity;
				if (((previousValue != value) 
							|| (this._The.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._The.Entity = null;
						previousValue.LichSuGiaoDiches.Remove(this);
					}
					this._The.Entity = value;
					if ((value != null))
					{
						value.LichSuGiaoDiches.Add(this);
						this._MaThe = value.MaThe;
					}
					else
					{
						this._MaThe = default(string);
					}
					this.SendPropertyChanged("The");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiThe")]
	public partial class LoaiThe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiThe;
		
		private string _TenLoaiThe;
		
		private System.Nullable<int> _TinhTrang;
		
		private EntitySet<The> _Thes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiTheChanging(string value);
    partial void OnMaLoaiTheChanged();
    partial void OnTenLoaiTheChanging(string value);
    partial void OnTenLoaiTheChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public LoaiThe()
		{
			this._Thes = new EntitySet<The>(new Action<The>(this.attach_Thes), new Action<The>(this.detach_Thes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiThe
		{
			get
			{
				return this._MaLoaiThe;
			}
			set
			{
				if ((this._MaLoaiThe != value))
				{
					this.OnMaLoaiTheChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThe = value;
					this.SendPropertyChanged("MaLoaiThe");
					this.OnMaLoaiTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiThe", DbType="NVarChar(50)")]
		public string TenLoaiThe
		{
			get
			{
				return this._TenLoaiThe;
			}
			set
			{
				if ((this._TenLoaiThe != value))
				{
					this.OnTenLoaiTheChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiThe = value;
					this.SendPropertyChanged("TenLoaiThe");
					this.OnTenLoaiTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThe_The", Storage="_Thes", ThisKey="MaLoaiThe", OtherKey="MaLoaiThe")]
		public EntitySet<The> Thes
		{
			get
			{
				return this._Thes;
			}
			set
			{
				this._Thes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thes(The entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThe = this;
		}
		
		private void detach_Thes(The entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MoiGioi")]
	public partial class MoiGioi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMoiGioi;
		
		private string _MaTaiKhoan;
		
		private string _TenCongTy;
		
		private System.Nullable<int> _DienThoaiCongTy;
		
		private string _SoGiayPhepKinhDoanh;
		
		private System.Nullable<int> _TinhTrang;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMoiGioiChanging(string value);
    partial void OnMaMoiGioiChanged();
    partial void OnMaTaiKhoanChanging(string value);
    partial void OnMaTaiKhoanChanged();
    partial void OnTenCongTyChanging(string value);
    partial void OnTenCongTyChanged();
    partial void OnDienThoaiCongTyChanging(System.Nullable<int> value);
    partial void OnDienThoaiCongTyChanged();
    partial void OnSoGiayPhepKinhDoanhChanging(string value);
    partial void OnSoGiayPhepKinhDoanhChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public MoiGioi()
		{
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMoiGioi", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMoiGioi
		{
			get
			{
				return this._MaMoiGioi;
			}
			set
			{
				if ((this._MaMoiGioi != value))
				{
					this.OnMaMoiGioiChanging(value);
					this.SendPropertyChanging();
					this._MaMoiGioi = value;
					this.SendPropertyChanged("MaMoiGioi");
					this.OnMaMoiGioiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoan", DbType="VarChar(10)")]
		public string MaTaiKhoan
		{
			get
			{
				return this._MaTaiKhoan;
			}
			set
			{
				if ((this._MaTaiKhoan != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoan = value;
					this.SendPropertyChanged("MaTaiKhoan");
					this.OnMaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTy", DbType="NVarChar(50)")]
		public string TenCongTy
		{
			get
			{
				return this._TenCongTy;
			}
			set
			{
				if ((this._TenCongTy != value))
				{
					this.OnTenCongTyChanging(value);
					this.SendPropertyChanging();
					this._TenCongTy = value;
					this.SendPropertyChanged("TenCongTy");
					this.OnTenCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiCongTy", DbType="Int")]
		public System.Nullable<int> DienThoaiCongTy
		{
			get
			{
				return this._DienThoaiCongTy;
			}
			set
			{
				if ((this._DienThoaiCongTy != value))
				{
					this.OnDienThoaiCongTyChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiCongTy = value;
					this.SendPropertyChanged("DienThoaiCongTy");
					this.OnDienThoaiCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGiayPhepKinhDoanh", DbType="NVarChar(50)")]
		public string SoGiayPhepKinhDoanh
		{
			get
			{
				return this._SoGiayPhepKinhDoanh;
			}
			set
			{
				if ((this._SoGiayPhepKinhDoanh != value))
				{
					this.OnSoGiayPhepKinhDoanhChanging(value);
					this.SendPropertyChanging();
					this._SoGiayPhepKinhDoanh = value;
					this.SendPropertyChanged("SoGiayPhepKinhDoanh");
					this.OnSoGiayPhepKinhDoanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_MoiGioi", Storage="_TaiKhoan", ThisKey="MaTaiKhoan", OtherKey="MaTaiKhoan", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.MoiGiois.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.MoiGiois.Add(this);
						this._MaTaiKhoan = value.MaTaiKhoan;
					}
					else
					{
						this._MaTaiKhoan = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTaiKhoan;
		
		private System.Nullable<int> _SoTaiKhoan;
		
		private string _MaLoaiTaiKhoan;
		
		private string _Email;
		
		private string _MatKhau;
		
		private string _MatKhauGiaoDich;
		
		private System.Nullable<int> _TinhTrang;
		
		private EntitySet<KhachHang> _KhachHangs;
		
		private EntitySet<DiaChi> _DiaChis;
		
		private EntitySet<MoiGioi> _MoiGiois;
		
		private EntitySet<The> _Thes;
		
		private EntityRef<LoaiTaiKhoan> _LoaiTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTaiKhoanChanging(string value);
    partial void OnMaTaiKhoanChanged();
    partial void OnSoTaiKhoanChanging(System.Nullable<int> value);
    partial void OnSoTaiKhoanChanged();
    partial void OnMaLoaiTaiKhoanChanging(string value);
    partial void OnMaLoaiTaiKhoanChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMatKhauGiaoDichChanging(string value);
    partial void OnMatKhauGiaoDichChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			this._DiaChis = new EntitySet<DiaChi>(new Action<DiaChi>(this.attach_DiaChis), new Action<DiaChi>(this.detach_DiaChis));
			this._MoiGiois = new EntitySet<MoiGioi>(new Action<MoiGioi>(this.attach_MoiGiois), new Action<MoiGioi>(this.detach_MoiGiois));
			this._Thes = new EntitySet<The>(new Action<The>(this.attach_Thes), new Action<The>(this.detach_Thes));
			this._LoaiTaiKhoan = default(EntityRef<LoaiTaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoan", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTaiKhoan
		{
			get
			{
				return this._MaTaiKhoan;
			}
			set
			{
				if ((this._MaTaiKhoan != value))
				{
					this.OnMaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoan = value;
					this.SendPropertyChanged("MaTaiKhoan");
					this.OnMaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTaiKhoan", DbType="Int")]
		public System.Nullable<int> SoTaiKhoan
		{
			get
			{
				return this._SoTaiKhoan;
			}
			set
			{
				if ((this._SoTaiKhoan != value))
				{
					this.OnSoTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._SoTaiKhoan = value;
					this.SendPropertyChanged("SoTaiKhoan");
					this.OnSoTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTaiKhoan", DbType="VarChar(10)")]
		public string MaLoaiTaiKhoan
		{
			get
			{
				return this._MaLoaiTaiKhoan;
			}
			set
			{
				if ((this._MaLoaiTaiKhoan != value))
				{
					if (this._LoaiTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTaiKhoan = value;
					this.SendPropertyChanged("MaLoaiTaiKhoan");
					this.OnMaLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauGiaoDich", DbType="VarChar(50)")]
		public string MatKhauGiaoDich
		{
			get
			{
				return this._MatKhauGiaoDich;
			}
			set
			{
				if ((this._MatKhauGiaoDich != value))
				{
					this.OnMatKhauGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._MatKhauGiaoDich = value;
					this.SendPropertyChanged("MatKhauGiaoDich");
					this.OnMatKhauGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_KhachHang", Storage="_KhachHangs", ThisKey="MaTaiKhoan", OtherKey="MaTaiKhoan")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_DiaChi", Storage="_DiaChis", ThisKey="MaTaiKhoan", OtherKey="MaTaiKhoan")]
		public EntitySet<DiaChi> DiaChis
		{
			get
			{
				return this._DiaChis;
			}
			set
			{
				this._DiaChis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_MoiGioi", Storage="_MoiGiois", ThisKey="MaTaiKhoan", OtherKey="MaTaiKhoan")]
		public EntitySet<MoiGioi> MoiGiois
		{
			get
			{
				return this._MoiGiois;
			}
			set
			{
				this._MoiGiois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_The", Storage="_Thes", ThisKey="MaTaiKhoan", OtherKey="MaTaiKhoan")]
		public EntitySet<The> Thes
		{
			get
			{
				return this._Thes;
			}
			set
			{
				this._Thes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTaiKhoan_TaiKhoan", Storage="_LoaiTaiKhoan", ThisKey="MaLoaiTaiKhoan", OtherKey="MaLoaiTaiKhoan", IsForeignKey=true)]
		public LoaiTaiKhoan LoaiTaiKhoan
		{
			get
			{
				return this._LoaiTaiKhoan.Entity;
			}
			set
			{
				LoaiTaiKhoan previousValue = this._LoaiTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._LoaiTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiTaiKhoan.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._LoaiTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaLoaiTaiKhoan = value.MaLoaiTaiKhoan;
					}
					else
					{
						this._MaLoaiTaiKhoan = default(string);
					}
					this.SendPropertyChanged("LoaiTaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_DiaChis(DiaChi entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_DiaChis(DiaChi entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_MoiGiois(MoiGioi entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_MoiGiois(MoiGioi entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_Thes(The entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_Thes(The entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThamSo")]
	public partial class ThamSo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThamSo;
		
		private string _TenThamSo;
		
		private string _Kieu;
		
		private string _GiaTri;
		
		private string _GhiChu;
		
		private System.Nullable<int> _TinhTrang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThamSoChanging(string value);
    partial void OnMaThamSoChanged();
    partial void OnTenThamSoChanging(string value);
    partial void OnTenThamSoChanged();
    partial void OnKieuChanging(string value);
    partial void OnKieuChanged();
    partial void OnGiaTriChanging(string value);
    partial void OnGiaTriChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public ThamSo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThamSo", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThamSo
		{
			get
			{
				return this._MaThamSo;
			}
			set
			{
				if ((this._MaThamSo != value))
				{
					this.OnMaThamSoChanging(value);
					this.SendPropertyChanging();
					this._MaThamSo = value;
					this.SendPropertyChanged("MaThamSo");
					this.OnMaThamSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThamSo", DbType="NVarChar(50)")]
		public string TenThamSo
		{
			get
			{
				return this._TenThamSo;
			}
			set
			{
				if ((this._TenThamSo != value))
				{
					this.OnTenThamSoChanging(value);
					this.SendPropertyChanging();
					this._TenThamSo = value;
					this.SendPropertyChanged("TenThamSo");
					this.OnTenThamSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kieu", DbType="VarChar(50)")]
		public string Kieu
		{
			get
			{
				return this._Kieu;
			}
			set
			{
				if ((this._Kieu != value))
				{
					this.OnKieuChanging(value);
					this.SendPropertyChanging();
					this._Kieu = value;
					this.SendPropertyChanged("Kieu");
					this.OnKieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTri", DbType="VarChar(10)")]
		public string GiaTri
		{
			get
			{
				return this._GiaTri;
			}
			set
			{
				if ((this._GiaTri != value))
				{
					this.OnGiaTriChanging(value);
					this.SendPropertyChanging();
					this._GiaTri = value;
					this.SendPropertyChanged("GiaTri");
					this.OnGiaTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.The")]
	public partial class The : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThe;
		
		private string _MaTaiKhoan;
		
		private string _MaLoaiThe;
		
		private string _SoThe;
		
		private string _SoPin;
		
		private string _SoBaoMat;
		
		private System.Nullable<decimal> _SoDu;
		
		private System.Nullable<System.DateTime> _NgayMoThe;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private System.Nullable<int> _TinhTrang;
		
		private EntitySet<LichSuGiaoDich> _LichSuGiaoDiches;
		
		private EntityRef<LoaiThe> _LoaiThe;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTheChanging(string value);
    partial void OnMaTheChanged();
    partial void OnMaTaiKhoanChanging(string value);
    partial void OnMaTaiKhoanChanged();
    partial void OnMaLoaiTheChanging(string value);
    partial void OnMaLoaiTheChanged();
    partial void OnSoTheChanging(string value);
    partial void OnSoTheChanged();
    partial void OnSoPinChanging(string value);
    partial void OnSoPinChanged();
    partial void OnSoBaoMatChanging(string value);
    partial void OnSoBaoMatChanged();
    partial void OnSoDuChanging(System.Nullable<decimal> value);
    partial void OnSoDuChanged();
    partial void OnNgayMoTheChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMoTheChanged();
    partial void OnNgayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public The()
		{
			this._LichSuGiaoDiches = new EntitySet<LichSuGiaoDich>(new Action<LichSuGiaoDich>(this.attach_LichSuGiaoDiches), new Action<LichSuGiaoDich>(this.detach_LichSuGiaoDiches));
			this._LoaiThe = default(EntityRef<LoaiThe>);
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThe
		{
			get
			{
				return this._MaThe;
			}
			set
			{
				if ((this._MaThe != value))
				{
					this.OnMaTheChanging(value);
					this.SendPropertyChanging();
					this._MaThe = value;
					this.SendPropertyChanged("MaThe");
					this.OnMaTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoan", DbType="VarChar(10)")]
		public string MaTaiKhoan
		{
			get
			{
				return this._MaTaiKhoan;
			}
			set
			{
				if ((this._MaTaiKhoan != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoan = value;
					this.SendPropertyChanged("MaTaiKhoan");
					this.OnMaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThe", DbType="VarChar(10)")]
		public string MaLoaiThe
		{
			get
			{
				return this._MaLoaiThe;
			}
			set
			{
				if ((this._MaLoaiThe != value))
				{
					if (this._LoaiThe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiTheChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThe = value;
					this.SendPropertyChanged("MaLoaiThe");
					this.OnMaLoaiTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThe", DbType="VarChar(16)")]
		public string SoThe
		{
			get
			{
				return this._SoThe;
			}
			set
			{
				if ((this._SoThe != value))
				{
					this.OnSoTheChanging(value);
					this.SendPropertyChanging();
					this._SoThe = value;
					this.SendPropertyChanged("SoThe");
					this.OnSoTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPin", DbType="VarChar(6)")]
		public string SoPin
		{
			get
			{
				return this._SoPin;
			}
			set
			{
				if ((this._SoPin != value))
				{
					this.OnSoPinChanging(value);
					this.SendPropertyChanging();
					this._SoPin = value;
					this.SendPropertyChanged("SoPin");
					this.OnSoPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBaoMat", DbType="VarChar(10)")]
		public string SoBaoMat
		{
			get
			{
				return this._SoBaoMat;
			}
			set
			{
				if ((this._SoBaoMat != value))
				{
					this.OnSoBaoMatChanging(value);
					this.SendPropertyChanging();
					this._SoBaoMat = value;
					this.SendPropertyChanged("SoBaoMat");
					this.OnSoBaoMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoDu
		{
			get
			{
				return this._SoDu;
			}
			set
			{
				if ((this._SoDu != value))
				{
					this.OnSoDuChanging(value);
					this.SendPropertyChanging();
					this._SoDu = value;
					this.SendPropertyChanged("SoDu");
					this.OnSoDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMoThe", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMoThe
		{
			get
			{
				return this._NgayMoThe;
			}
			set
			{
				if ((this._NgayMoThe != value))
				{
					this.OnNgayMoTheChanging(value);
					this.SendPropertyChanging();
					this._NgayMoThe = value;
					this.SendPropertyChanged("NgayMoThe");
					this.OnNgayMoTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="The_LichSuGiaoDich", Storage="_LichSuGiaoDiches", ThisKey="MaThe", OtherKey="MaThe")]
		public EntitySet<LichSuGiaoDich> LichSuGiaoDiches
		{
			get
			{
				return this._LichSuGiaoDiches;
			}
			set
			{
				this._LichSuGiaoDiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThe_The", Storage="_LoaiThe", ThisKey="MaLoaiThe", OtherKey="MaLoaiThe", IsForeignKey=true)]
		public LoaiThe LoaiThe
		{
			get
			{
				return this._LoaiThe.Entity;
			}
			set
			{
				LoaiThe previousValue = this._LoaiThe.Entity;
				if (((previousValue != value) 
							|| (this._LoaiThe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiThe.Entity = null;
						previousValue.Thes.Remove(this);
					}
					this._LoaiThe.Entity = value;
					if ((value != null))
					{
						value.Thes.Add(this);
						this._MaLoaiThe = value.MaLoaiThe;
					}
					else
					{
						this._MaLoaiThe = default(string);
					}
					this.SendPropertyChanged("LoaiThe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_The", Storage="_TaiKhoan", ThisKey="MaTaiKhoan", OtherKey="MaTaiKhoan", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.Thes.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.Thes.Add(this);
						this._MaTaiKhoan = value.MaTaiKhoan;
					}
					else
					{
						this._MaTaiKhoan = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichSuGiaoDiches(LichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.The = this;
		}
		
		private void detach_LichSuGiaoDiches(LichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.The = null;
		}
	}
}
#pragma warning restore 1591
