#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSWorkFlow
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NganHang")]
	public partial class dbNganHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCaNhan(CaNhan instance);
    partial void UpdateCaNhan(CaNhan instance);
    partial void DeleteCaNhan(CaNhan instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertDoanhNghiep(DoanhNghiep instance);
    partial void UpdateDoanhNghiep(DoanhNghiep instance);
    partial void DeleteDoanhNghiep(DoanhNghiep instance);
    #endregion
		
		public dbNganHangDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NganHangConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CaNhan> CaNhans
		{
			get
			{
				return this.GetTable<CaNhan>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DoanhNghiep> DoanhNghieps
		{
			get
			{
				return this.GetTable<DoanhNghiep>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaNhan")]
	public partial class CaNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCaNhan;
		
		private string _MaKhachHang;
		
		private System.Nullable<int> _CMND_HoChieu;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCaNhanChanging(string value);
    partial void OnMaCaNhanChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnCMND_HoChieuChanging(System.Nullable<int> value);
    partial void OnCMND_HoChieuChanged();
    #endregion
		
		public CaNhan()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCaNhan", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCaNhan
		{
			get
			{
				return this._MaCaNhan;
			}
			set
			{
				if ((this._MaCaNhan != value))
				{
					this.OnMaCaNhanChanging(value);
					this.SendPropertyChanging();
					this._MaCaNhan = value;
					this.SendPropertyChanged("MaCaNhan");
					this.OnMaCaNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(7)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND_HoChieu", DbType="Int")]
		public System.Nullable<int> CMND_HoChieu
		{
			get
			{
				return this._CMND_HoChieu;
			}
			set
			{
				if ((this._CMND_HoChieu != value))
				{
					this.OnCMND_HoChieuChanging(value);
					this.SendPropertyChanging();
					this._CMND_HoChieu = value;
					this.SendPropertyChanged("CMND_HoChieu");
					this.OnCMND_HoChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_CaNhan", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.CaNhans.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.CaNhans.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _Email;
		
		private string _MatKhau;
		
		private string _MatKhauThanhToan;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _MaDiaChi;
		
		private System.Nullable<int> _DienThoai;
		
		private EntitySet<CaNhan> _CaNhans;
		
		private EntitySet<DoanhNghiep> _DoanhNghieps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMatKhauThanhToanChanging(string value);
    partial void OnMatKhauThanhToanChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnMaDiaChiChanging(string value);
    partial void OnMaDiaChiChanged();
    partial void OnDienThoaiChanging(System.Nullable<int> value);
    partial void OnDienThoaiChanged();
    #endregion
		
		public KhachHang()
		{
			this._CaNhans = new EntitySet<CaNhan>(new Action<CaNhan>(this.attach_CaNhans), new Action<CaNhan>(this.detach_CaNhans));
			this._DoanhNghieps = new EntitySet<DoanhNghiep>(new Action<DoanhNghiep>(this.attach_DoanhNghieps), new Action<DoanhNghiep>(this.detach_DoanhNghieps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauThanhToan", DbType="VarChar(7)")]
		public string MatKhauThanhToan
		{
			get
			{
				return this._MatKhauThanhToan;
			}
			set
			{
				if ((this._MatKhauThanhToan != value))
				{
					this.OnMatKhauThanhToanChanging(value);
					this.SendPropertyChanging();
					this._MatKhauThanhToan = value;
					this.SendPropertyChanged("MatKhauThanhToan");
					this.OnMatKhauThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(MAX)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaChi", DbType="VarChar(7)")]
		public string MaDiaChi
		{
			get
			{
				return this._MaDiaChi;
			}
			set
			{
				if ((this._MaDiaChi != value))
				{
					this.OnMaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._MaDiaChi = value;
					this.SendPropertyChanged("MaDiaChi");
					this.OnMaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="Int")]
		public System.Nullable<int> DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_CaNhan", Storage="_CaNhans", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<CaNhan> CaNhans
		{
			get
			{
				return this._CaNhans;
			}
			set
			{
				this._CaNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DoanhNghiep", Storage="_DoanhNghieps", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<DoanhNghiep> DoanhNghieps
		{
			get
			{
				return this._DoanhNghieps;
			}
			set
			{
				this._DoanhNghieps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CaNhans(CaNhan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_CaNhans(CaNhan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_DoanhNghieps(DoanhNghiep entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DoanhNghieps(DoanhNghiep entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanhNghiep")]
	public partial class DoanhNghiep : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDoanhNghiep;
		
		private string _MaKhachHang;
		
		private string _MaLoaiGiayPhep;
		
		private string _TenDoanhNghiep;
		
		private System.Nullable<int> _DienThoaiDoanhNghiep;
		
		private string _SoGiayPhepKinhDoanh;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoanhNghiepChanging(string value);
    partial void OnMaDoanhNghiepChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnMaLoaiGiayPhepChanging(string value);
    partial void OnMaLoaiGiayPhepChanged();
    partial void OnTenDoanhNghiepChanging(string value);
    partial void OnTenDoanhNghiepChanged();
    partial void OnDienThoaiDoanhNghiepChanging(System.Nullable<int> value);
    partial void OnDienThoaiDoanhNghiepChanged();
    partial void OnSoGiayPhepKinhDoanhChanging(string value);
    partial void OnSoGiayPhepKinhDoanhChanged();
    #endregion
		
		public DoanhNghiep()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoanhNghiep", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoanhNghiep
		{
			get
			{
				return this._MaDoanhNghiep;
			}
			set
			{
				if ((this._MaDoanhNghiep != value))
				{
					this.OnMaDoanhNghiepChanging(value);
					this.SendPropertyChanging();
					this._MaDoanhNghiep = value;
					this.SendPropertyChanged("MaDoanhNghiep");
					this.OnMaDoanhNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(7)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGiayPhep", DbType="VarChar(7)")]
		public string MaLoaiGiayPhep
		{
			get
			{
				return this._MaLoaiGiayPhep;
			}
			set
			{
				if ((this._MaLoaiGiayPhep != value))
				{
					this.OnMaLoaiGiayPhepChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGiayPhep = value;
					this.SendPropertyChanged("MaLoaiGiayPhep");
					this.OnMaLoaiGiayPhepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoanhNghiep", DbType="NChar(10)")]
		public string TenDoanhNghiep
		{
			get
			{
				return this._TenDoanhNghiep;
			}
			set
			{
				if ((this._TenDoanhNghiep != value))
				{
					this.OnTenDoanhNghiepChanging(value);
					this.SendPropertyChanging();
					this._TenDoanhNghiep = value;
					this.SendPropertyChanged("TenDoanhNghiep");
					this.OnTenDoanhNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiDoanhNghiep", DbType="Int")]
		public System.Nullable<int> DienThoaiDoanhNghiep
		{
			get
			{
				return this._DienThoaiDoanhNghiep;
			}
			set
			{
				if ((this._DienThoaiDoanhNghiep != value))
				{
					this.OnDienThoaiDoanhNghiepChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiDoanhNghiep = value;
					this.SendPropertyChanged("DienThoaiDoanhNghiep");
					this.OnDienThoaiDoanhNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGiayPhepKinhDoanh", DbType="NChar(10)")]
		public string SoGiayPhepKinhDoanh
		{
			get
			{
				return this._SoGiayPhepKinhDoanh;
			}
			set
			{
				if ((this._SoGiayPhepKinhDoanh != value))
				{
					this.OnSoGiayPhepKinhDoanhChanging(value);
					this.SendPropertyChanging();
					this._SoGiayPhepKinhDoanh = value;
					this.SendPropertyChanged("SoGiayPhepKinhDoanh");
					this.OnSoGiayPhepKinhDoanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DoanhNghiep", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DoanhNghieps.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DoanhNghieps.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
