#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSWorkFlow
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NganHang")]
	public partial class dbNganHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCaNhan(CaNhan instance);
    partial void UpdateCaNhan(CaNhan instance);
    partial void DeleteCaNhan(CaNhan instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertDoanhNghiep(DoanhNghiep instance);
    partial void UpdateDoanhNghiep(DoanhNghiep instance);
    partial void DeleteDoanhNghiep(DoanhNghiep instance);
    partial void InsertLoaiThe(LoaiThe instance);
    partial void UpdateLoaiThe(LoaiThe instance);
    partial void DeleteLoaiThe(LoaiThe instance);
    partial void InsertLichSuGiaoDich(LichSuGiaoDich instance);
    partial void UpdateLichSuGiaoDich(LichSuGiaoDich instance);
    partial void DeleteLichSuGiaoDich(LichSuGiaoDich instance);
    partial void InsertLoaiGiaoDich(LoaiGiaoDich instance);
    partial void UpdateLoaiGiaoDich(LoaiGiaoDich instance);
    partial void DeleteLoaiGiaoDich(LoaiGiaoDich instance);
    partial void InsertThe(The instance);
    partial void UpdateThe(The instance);
    partial void DeleteThe(The instance);
    #endregion
		
		public dbNganHangDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NganHangConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbNganHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CaNhan> CaNhans
		{
			get
			{
				return this.GetTable<CaNhan>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DoanhNghiep> DoanhNghieps
		{
			get
			{
				return this.GetTable<DoanhNghiep>();
			}
		}
		
		public System.Data.Linq.Table<LoaiThe> LoaiThes
		{
			get
			{
				return this.GetTable<LoaiThe>();
			}
		}
		
		public System.Data.Linq.Table<LichSuGiaoDich> LichSuGiaoDiches
		{
			get
			{
				return this.GetTable<LichSuGiaoDich>();
			}
		}
		
		public System.Data.Linq.Table<LoaiGiaoDich> LoaiGiaoDiches
		{
			get
			{
				return this.GetTable<LoaiGiaoDich>();
			}
		}
		
		public System.Data.Linq.Table<The> Thes
		{
			get
			{
				return this.GetTable<The>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaNhan")]
	public partial class CaNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCaNhan;
		
		private string _MaKhachHang;
		
		private System.Nullable<int> _CMND_HoChieu;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCaNhanChanging(string value);
    partial void OnMaCaNhanChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnCMND_HoChieuChanging(System.Nullable<int> value);
    partial void OnCMND_HoChieuChanged();
    #endregion
		
		public CaNhan()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCaNhan", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCaNhan
		{
			get
			{
				return this._MaCaNhan;
			}
			set
			{
				if ((this._MaCaNhan != value))
				{
					this.OnMaCaNhanChanging(value);
					this.SendPropertyChanging();
					this._MaCaNhan = value;
					this.SendPropertyChanged("MaCaNhan");
					this.OnMaCaNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(7)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND_HoChieu", DbType="Int")]
		public System.Nullable<int> CMND_HoChieu
		{
			get
			{
				return this._CMND_HoChieu;
			}
			set
			{
				if ((this._CMND_HoChieu != value))
				{
					this.OnCMND_HoChieuChanging(value);
					this.SendPropertyChanging();
					this._CMND_HoChieu = value;
					this.SendPropertyChanged("CMND_HoChieu");
					this.OnCMND_HoChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_CaNhan", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.CaNhans.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.CaNhans.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _Email;
		
		private string _MatKhau;
		
		private string _MatKhauThanhToan;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _MaDiaChi;
		
		private System.Nullable<int> _DienThoai;
		
		private EntitySet<CaNhan> _CaNhans;
		
		private EntitySet<DoanhNghiep> _DoanhNghieps;
		
		private EntitySet<The> _Thes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMatKhauThanhToanChanging(string value);
    partial void OnMatKhauThanhToanChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnMaDiaChiChanging(string value);
    partial void OnMaDiaChiChanged();
    partial void OnDienThoaiChanging(System.Nullable<int> value);
    partial void OnDienThoaiChanged();
    #endregion
		
		public KhachHang()
		{
			this._CaNhans = new EntitySet<CaNhan>(new Action<CaNhan>(this.attach_CaNhans), new Action<CaNhan>(this.detach_CaNhans));
			this._DoanhNghieps = new EntitySet<DoanhNghiep>(new Action<DoanhNghiep>(this.attach_DoanhNghieps), new Action<DoanhNghiep>(this.detach_DoanhNghieps));
			this._Thes = new EntitySet<The>(new Action<The>(this.attach_Thes), new Action<The>(this.detach_Thes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauThanhToan", DbType="VarChar(7)")]
		public string MatKhauThanhToan
		{
			get
			{
				return this._MatKhauThanhToan;
			}
			set
			{
				if ((this._MatKhauThanhToan != value))
				{
					this.OnMatKhauThanhToanChanging(value);
					this.SendPropertyChanging();
					this._MatKhauThanhToan = value;
					this.SendPropertyChanged("MatKhauThanhToan");
					this.OnMatKhauThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(MAX)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaChi", DbType="VarChar(7)")]
		public string MaDiaChi
		{
			get
			{
				return this._MaDiaChi;
			}
			set
			{
				if ((this._MaDiaChi != value))
				{
					this.OnMaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._MaDiaChi = value;
					this.SendPropertyChanged("MaDiaChi");
					this.OnMaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="Int")]
		public System.Nullable<int> DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_CaNhan", Storage="_CaNhans", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<CaNhan> CaNhans
		{
			get
			{
				return this._CaNhans;
			}
			set
			{
				this._CaNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DoanhNghiep", Storage="_DoanhNghieps", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<DoanhNghiep> DoanhNghieps
		{
			get
			{
				return this._DoanhNghieps;
			}
			set
			{
				this._DoanhNghieps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_The", Storage="_Thes", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<The> Thes
		{
			get
			{
				return this._Thes;
			}
			set
			{
				this._Thes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CaNhans(CaNhan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_CaNhans(CaNhan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_DoanhNghieps(DoanhNghiep entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DoanhNghieps(DoanhNghiep entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_Thes(The entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_Thes(The entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanhNghiep")]
	public partial class DoanhNghiep : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDoanhNghiep;
		
		private string _MaKhachHang;
		
		private string _MaLoaiGiayPhep;
		
		private string _TenDoanhNghiep;
		
		private System.Nullable<int> _DienThoaiDoanhNghiep;
		
		private string _SoGiayPhepKinhDoanh;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoanhNghiepChanging(string value);
    partial void OnMaDoanhNghiepChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnMaLoaiGiayPhepChanging(string value);
    partial void OnMaLoaiGiayPhepChanged();
    partial void OnTenDoanhNghiepChanging(string value);
    partial void OnTenDoanhNghiepChanged();
    partial void OnDienThoaiDoanhNghiepChanging(System.Nullable<int> value);
    partial void OnDienThoaiDoanhNghiepChanged();
    partial void OnSoGiayPhepKinhDoanhChanging(string value);
    partial void OnSoGiayPhepKinhDoanhChanged();
    #endregion
		
		public DoanhNghiep()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoanhNghiep", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoanhNghiep
		{
			get
			{
				return this._MaDoanhNghiep;
			}
			set
			{
				if ((this._MaDoanhNghiep != value))
				{
					this.OnMaDoanhNghiepChanging(value);
					this.SendPropertyChanging();
					this._MaDoanhNghiep = value;
					this.SendPropertyChanged("MaDoanhNghiep");
					this.OnMaDoanhNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(7)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGiayPhep", DbType="VarChar(7)")]
		public string MaLoaiGiayPhep
		{
			get
			{
				return this._MaLoaiGiayPhep;
			}
			set
			{
				if ((this._MaLoaiGiayPhep != value))
				{
					this.OnMaLoaiGiayPhepChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGiayPhep = value;
					this.SendPropertyChanged("MaLoaiGiayPhep");
					this.OnMaLoaiGiayPhepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoanhNghiep", DbType="NChar(10)")]
		public string TenDoanhNghiep
		{
			get
			{
				return this._TenDoanhNghiep;
			}
			set
			{
				if ((this._TenDoanhNghiep != value))
				{
					this.OnTenDoanhNghiepChanging(value);
					this.SendPropertyChanging();
					this._TenDoanhNghiep = value;
					this.SendPropertyChanged("TenDoanhNghiep");
					this.OnTenDoanhNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiDoanhNghiep", DbType="Int")]
		public System.Nullable<int> DienThoaiDoanhNghiep
		{
			get
			{
				return this._DienThoaiDoanhNghiep;
			}
			set
			{
				if ((this._DienThoaiDoanhNghiep != value))
				{
					this.OnDienThoaiDoanhNghiepChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiDoanhNghiep = value;
					this.SendPropertyChanged("DienThoaiDoanhNghiep");
					this.OnDienThoaiDoanhNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGiayPhepKinhDoanh", DbType="NChar(10)")]
		public string SoGiayPhepKinhDoanh
		{
			get
			{
				return this._SoGiayPhepKinhDoanh;
			}
			set
			{
				if ((this._SoGiayPhepKinhDoanh != value))
				{
					this.OnSoGiayPhepKinhDoanhChanging(value);
					this.SendPropertyChanging();
					this._SoGiayPhepKinhDoanh = value;
					this.SendPropertyChanged("SoGiayPhepKinhDoanh");
					this.OnSoGiayPhepKinhDoanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DoanhNghiep", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DoanhNghieps.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DoanhNghieps.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiThe")]
	public partial class LoaiThe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiThe;
		
		private string _TenLoaiThe;
		
		private EntitySet<The> _Thes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiTheChanging(string value);
    partial void OnMaLoaiTheChanged();
    partial void OnTenLoaiTheChanging(string value);
    partial void OnTenLoaiTheChanged();
    #endregion
		
		public LoaiThe()
		{
			this._Thes = new EntitySet<The>(new Action<The>(this.attach_Thes), new Action<The>(this.detach_Thes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThe", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiThe
		{
			get
			{
				return this._MaLoaiThe;
			}
			set
			{
				if ((this._MaLoaiThe != value))
				{
					this.OnMaLoaiTheChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThe = value;
					this.SendPropertyChanged("MaLoaiThe");
					this.OnMaLoaiTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiThe", DbType="VarChar(50)")]
		public string TenLoaiThe
		{
			get
			{
				return this._TenLoaiThe;
			}
			set
			{
				if ((this._TenLoaiThe != value))
				{
					this.OnTenLoaiTheChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiThe = value;
					this.SendPropertyChanged("TenLoaiThe");
					this.OnTenLoaiTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThe_The", Storage="_Thes", ThisKey="MaLoaiThe", OtherKey="MaLoaiThe")]
		public EntitySet<The> Thes
		{
			get
			{
				return this._Thes;
			}
			set
			{
				this._Thes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thes(The entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThe = this;
		}
		
		private void detach_Thes(The entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichSuGiaoDich")]
	public partial class LichSuGiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiaoDich;
		
		private string _MaThe;
		
		private string _SoTheNhan;
		
		private System.Nullable<System.DateTime> _NgayGiaoDich;
		
		private string _MaLoaiGiaoDich;
		
		private System.Nullable<decimal> _SoTienGiaoDich;
		
		private EntityRef<LoaiGiaoDich> _LoaiGiaoDich;
		
		private EntityRef<The> _The;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaoDichChanging(string value);
    partial void OnMaGiaoDichChanged();
    partial void OnMaTheChanging(string value);
    partial void OnMaTheChanged();
    partial void OnSoTheNhanChanging(string value);
    partial void OnSoTheNhanChanged();
    partial void OnNgayGiaoDichChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoDichChanged();
    partial void OnMaLoaiGiaoDichChanging(string value);
    partial void OnMaLoaiGiaoDichChanged();
    partial void OnSoTienGiaoDichChanging(System.Nullable<decimal> value);
    partial void OnSoTienGiaoDichChanged();
    #endregion
		
		public LichSuGiaoDich()
		{
			this._LoaiGiaoDich = default(EntityRef<LoaiGiaoDich>);
			this._The = default(EntityRef<The>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaoDich", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiaoDich
		{
			get
			{
				return this._MaGiaoDich;
			}
			set
			{
				if ((this._MaGiaoDich != value))
				{
					this.OnMaGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._MaGiaoDich = value;
					this.SendPropertyChanged("MaGiaoDich");
					this.OnMaGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThe", DbType="VarChar(7)")]
		public string MaThe
		{
			get
			{
				return this._MaThe;
			}
			set
			{
				if ((this._MaThe != value))
				{
					if (this._The.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTheChanging(value);
					this.SendPropertyChanging();
					this._MaThe = value;
					this.SendPropertyChanged("MaThe");
					this.OnMaTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTheNhan", DbType="VarChar(7)")]
		public string SoTheNhan
		{
			get
			{
				return this._SoTheNhan;
			}
			set
			{
				if ((this._SoTheNhan != value))
				{
					this.OnSoTheNhanChanging(value);
					this.SendPropertyChanging();
					this._SoTheNhan = value;
					this.SendPropertyChanged("SoTheNhan");
					this.OnSoTheNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoDich", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGiaoDich
		{
			get
			{
				return this._NgayGiaoDich;
			}
			set
			{
				if ((this._NgayGiaoDich != value))
				{
					this.OnNgayGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoDich = value;
					this.SendPropertyChanged("NgayGiaoDich");
					this.OnNgayGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGiaoDich", DbType="VarChar(7)")]
		public string MaLoaiGiaoDich
		{
			get
			{
				return this._MaLoaiGiaoDich;
			}
			set
			{
				if ((this._MaLoaiGiaoDich != value))
				{
					if (this._LoaiGiaoDich.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGiaoDich = value;
					this.SendPropertyChanged("MaLoaiGiaoDich");
					this.OnMaLoaiGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienGiaoDich", DbType="Money")]
		public System.Nullable<decimal> SoTienGiaoDich
		{
			get
			{
				return this._SoTienGiaoDich;
			}
			set
			{
				if ((this._SoTienGiaoDich != value))
				{
					this.OnSoTienGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._SoTienGiaoDich = value;
					this.SendPropertyChanged("SoTienGiaoDich");
					this.OnSoTienGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiGiaoDich_LichSuGiaoDich", Storage="_LoaiGiaoDich", ThisKey="MaLoaiGiaoDich", OtherKey="MaLoaiGiaoDich", IsForeignKey=true)]
		public LoaiGiaoDich LoaiGiaoDich
		{
			get
			{
				return this._LoaiGiaoDich.Entity;
			}
			set
			{
				LoaiGiaoDich previousValue = this._LoaiGiaoDich.Entity;
				if (((previousValue != value) 
							|| (this._LoaiGiaoDich.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiGiaoDich.Entity = null;
						previousValue.LichSuGiaoDiches.Remove(this);
					}
					this._LoaiGiaoDich.Entity = value;
					if ((value != null))
					{
						value.LichSuGiaoDiches.Add(this);
						this._MaLoaiGiaoDich = value.MaLoaiGiaoDich;
					}
					else
					{
						this._MaLoaiGiaoDich = default(string);
					}
					this.SendPropertyChanged("LoaiGiaoDich");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="The_LichSuGiaoDich", Storage="_The", ThisKey="MaThe", OtherKey="MaThe", IsForeignKey=true)]
		public The The
		{
			get
			{
				return this._The.Entity;
			}
			set
			{
				The previousValue = this._The.Entity;
				if (((previousValue != value) 
							|| (this._The.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._The.Entity = null;
						previousValue.LichSuGiaoDiches.Remove(this);
					}
					this._The.Entity = value;
					if ((value != null))
					{
						value.LichSuGiaoDiches.Add(this);
						this._MaThe = value.MaThe;
					}
					else
					{
						this._MaThe = default(string);
					}
					this.SendPropertyChanged("The");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiGiaoDich")]
	public partial class LoaiGiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiGiaoDich;
		
		private string _TenLoaiGiaoDich;
		
		private EntitySet<LichSuGiaoDich> _LichSuGiaoDiches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiGiaoDichChanging(string value);
    partial void OnMaLoaiGiaoDichChanged();
    partial void OnTenLoaiGiaoDichChanging(string value);
    partial void OnTenLoaiGiaoDichChanged();
    #endregion
		
		public LoaiGiaoDich()
		{
			this._LichSuGiaoDiches = new EntitySet<LichSuGiaoDich>(new Action<LichSuGiaoDich>(this.attach_LichSuGiaoDiches), new Action<LichSuGiaoDich>(this.detach_LichSuGiaoDiches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGiaoDich", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiGiaoDich
		{
			get
			{
				return this._MaLoaiGiaoDich;
			}
			set
			{
				if ((this._MaLoaiGiaoDich != value))
				{
					this.OnMaLoaiGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGiaoDich = value;
					this.SendPropertyChanged("MaLoaiGiaoDich");
					this.OnMaLoaiGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiGiaoDich", DbType="VarChar(50)")]
		public string TenLoaiGiaoDich
		{
			get
			{
				return this._TenLoaiGiaoDich;
			}
			set
			{
				if ((this._TenLoaiGiaoDich != value))
				{
					this.OnTenLoaiGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiGiaoDich = value;
					this.SendPropertyChanged("TenLoaiGiaoDich");
					this.OnTenLoaiGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiGiaoDich_LichSuGiaoDich", Storage="_LichSuGiaoDiches", ThisKey="MaLoaiGiaoDich", OtherKey="MaLoaiGiaoDich")]
		public EntitySet<LichSuGiaoDich> LichSuGiaoDiches
		{
			get
			{
				return this._LichSuGiaoDiches;
			}
			set
			{
				this._LichSuGiaoDiches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichSuGiaoDiches(LichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.LoaiGiaoDich = this;
		}
		
		private void detach_LichSuGiaoDiches(LichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.LoaiGiaoDich = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.The")]
	public partial class The : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThe;
		
		private string _MaLoaiThe;
		
		private string _MaKhachHang;
		
		private string _SoPin;
		
		private System.Nullable<decimal> _SoDu;
		
		private System.Nullable<System.DateTime> _NgayMoThe;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private System.Nullable<int> _TinhTrang;
		
		private string _MaSoThe;
		
		private string _MaBaoVe;
		
		private EntitySet<LichSuGiaoDich> _LichSuGiaoDiches;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LoaiThe> _LoaiThe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTheChanging(string value);
    partial void OnMaTheChanged();
    partial void OnMaLoaiTheChanging(string value);
    partial void OnMaLoaiTheChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnSoPinChanging(string value);
    partial void OnSoPinChanged();
    partial void OnSoDuChanging(System.Nullable<decimal> value);
    partial void OnSoDuChanged();
    partial void OnNgayMoTheChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMoTheChanged();
    partial void OnNgayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    partial void OnMaSoTheChanging(string value);
    partial void OnMaSoTheChanged();
    partial void OnMaBaoVeChanging(string value);
    partial void OnMaBaoVeChanged();
    #endregion
		
		public The()
		{
			this._LichSuGiaoDiches = new EntitySet<LichSuGiaoDich>(new Action<LichSuGiaoDich>(this.attach_LichSuGiaoDiches), new Action<LichSuGiaoDich>(this.detach_LichSuGiaoDiches));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LoaiThe = default(EntityRef<LoaiThe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThe", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThe
		{
			get
			{
				return this._MaThe;
			}
			set
			{
				if ((this._MaThe != value))
				{
					this.OnMaTheChanging(value);
					this.SendPropertyChanging();
					this._MaThe = value;
					this.SendPropertyChanged("MaThe");
					this.OnMaTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThe", DbType="VarChar(7)")]
		public string MaLoaiThe
		{
			get
			{
				return this._MaLoaiThe;
			}
			set
			{
				if ((this._MaLoaiThe != value))
				{
					if (this._LoaiThe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiTheChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThe = value;
					this.SendPropertyChanged("MaLoaiThe");
					this.OnMaLoaiTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(7)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPin", DbType="VarChar(50)")]
		public string SoPin
		{
			get
			{
				return this._SoPin;
			}
			set
			{
				if ((this._SoPin != value))
				{
					this.OnSoPinChanging(value);
					this.SendPropertyChanging();
					this._SoPin = value;
					this.SendPropertyChanged("SoPin");
					this.OnSoPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDu", DbType="Money")]
		public System.Nullable<decimal> SoDu
		{
			get
			{
				return this._SoDu;
			}
			set
			{
				if ((this._SoDu != value))
				{
					this.OnSoDuChanging(value);
					this.SendPropertyChanging();
					this._SoDu = value;
					this.SendPropertyChanged("SoDu");
					this.OnSoDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMoThe", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMoThe
		{
			get
			{
				return this._NgayMoThe;
			}
			set
			{
				if ((this._NgayMoThe != value))
				{
					this.OnNgayMoTheChanging(value);
					this.SendPropertyChanging();
					this._NgayMoThe = value;
					this.SendPropertyChanged("NgayMoThe");
					this.OnNgayMoTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoThe", DbType="NChar(16)")]
		public string MaSoThe
		{
			get
			{
				return this._MaSoThe;
			}
			set
			{
				if ((this._MaSoThe != value))
				{
					this.OnMaSoTheChanging(value);
					this.SendPropertyChanging();
					this._MaSoThe = value;
					this.SendPropertyChanged("MaSoThe");
					this.OnMaSoTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaoVe", DbType="NChar(10)")]
		public string MaBaoVe
		{
			get
			{
				return this._MaBaoVe;
			}
			set
			{
				if ((this._MaBaoVe != value))
				{
					this.OnMaBaoVeChanging(value);
					this.SendPropertyChanging();
					this._MaBaoVe = value;
					this.SendPropertyChanged("MaBaoVe");
					this.OnMaBaoVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="The_LichSuGiaoDich", Storage="_LichSuGiaoDiches", ThisKey="MaThe", OtherKey="MaThe")]
		public EntitySet<LichSuGiaoDich> LichSuGiaoDiches
		{
			get
			{
				return this._LichSuGiaoDiches;
			}
			set
			{
				this._LichSuGiaoDiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_The", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.Thes.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.Thes.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThe_The", Storage="_LoaiThe", ThisKey="MaLoaiThe", OtherKey="MaLoaiThe", IsForeignKey=true)]
		public LoaiThe LoaiThe
		{
			get
			{
				return this._LoaiThe.Entity;
			}
			set
			{
				LoaiThe previousValue = this._LoaiThe.Entity;
				if (((previousValue != value) 
							|| (this._LoaiThe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiThe.Entity = null;
						previousValue.Thes.Remove(this);
					}
					this._LoaiThe.Entity = value;
					if ((value != null))
					{
						value.Thes.Add(this);
						this._MaLoaiThe = value.MaLoaiThe;
					}
					else
					{
						this._MaLoaiThe = default(string);
					}
					this.SendPropertyChanged("LoaiThe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichSuGiaoDiches(LichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.The = this;
		}
		
		private void detach_LichSuGiaoDiches(LichSuGiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.The = null;
		}
	}
}
#pragma warning restore 1591
