<?xml version="1.0" encoding="utf-8"?><Database Name="xnvaufit_MoiGioi" Class="dbMoiGioiOnlineDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=123.30.174.126;Initial Catalog=xnvaufit_MoiGioi;Persist Security Info=True;User ID=xnvaufit_moigioi" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="xnvaufit_MoiGioiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="MaAdmin" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.The" Member="Thes">
    <Type Name="The">
      <Column Name="MaThe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTaiKhoan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaLoaiThe" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoThe" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="SoBaoMat" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayMoThe" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="The_LichSuGiaoDich" Member="LichSuGiaoDiches" ThisKey="MaThe" OtherKey="MaThe" Type="LichSuGiaoDich" />
      <Association Name="LoaiThe_The" Member="LoaiThe" ThisKey="MaLoaiThe" OtherKey="MaLoaiThe" Type="LoaiThe" IsForeignKey="true" />
      <Association Name="TaiKhoan_The" Member="TaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CaNhan" Member="CaNhans">
    <Type Name="CaNhan">
      <Column Name="MaCaNhan" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTaiKhoan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CMNDHoChieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="TaiKhoan_CaNhan" Member="TaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiaChi" Member="DiaChis">
    <Type Name="DiaChi">
      <Column Name="MaDiaChi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTaiKhoan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoNha" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Duong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhuongXa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuanHuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhThanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TaiKhoan_DiaChi" Member="TaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoanhNghiep" Member="DoanhNghieps">
    <Type Name="DoanhNghiep">
      <Column Name="MaDoanhNghiep" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTaiKhoan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaLoaiGiayPhepKinhDoanh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TenCongTy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoaiCongTy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoGiayPhepKinhDoanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaChiCongTy" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DienThoaiDiDong" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Association Name="LoaiGiayPhepKinhDoanh_DoanhNghiep" Member="LoaiGiayPhepKinhDoanh" ThisKey="MaLoaiGiayPhepKinhDoanh" OtherKey="MaLoaiGiayPhepKinhDoanh" Type="LoaiGiayPhepKinhDoanh" IsForeignKey="true" />
      <Association Name="TaiKhoan_DoanhNghiep" Member="TaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Groups">
    <Type Name="Group">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuGiaoDich" Member="LichSuGiaoDiches">
    <Type Name="LichSuGiaoDich">
      <Column Name="MaLichSuGiaoDich" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThe" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaLoaiGiaoDich" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoTheNhan" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="NgayGiaoDich" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTienGiaoDich" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="The_LichSuGiaoDich" Member="The" ThisKey="MaThe" OtherKey="MaThe" Type="The" IsForeignKey="true" />
      <Association Name="LoaiGiaoDich_LichSuGiaoDich" Member="LoaiGiaoDich" ThisKey="MaLoaiGiaoDich" OtherKey="MaLoaiGiaoDich" Type="LoaiGiaoDich" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiGiaoDich" Member="LoaiGiaoDiches">
    <Type Name="LoaiGiaoDich">
      <Column Name="MaLoaiGiaoDich" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiGiaoDich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiGiaoDich_LichSuGiaoDich" Member="LichSuGiaoDiches" ThisKey="MaLoaiGiaoDich" OtherKey="MaLoaiGiaoDich" Type="LichSuGiaoDich" />
      <Association Name="LoaiGiaoDich_PhiGiaoDich" Member="PhiGiaoDiches" ThisKey="MaLoaiGiaoDich" OtherKey="MaLoaiGiaoDich" Type="PhiGiaoDich" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiGiayPhepKinhDoanh" Member="LoaiGiayPhepKinhDoanhs">
    <Type Name="LoaiGiayPhepKinhDoanh">
      <Column Name="MaLoaiGiayPhepKinhDoanh" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiGiayPhepKinhDoanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiGiayPhepKinhDoanh_DoanhNghiep" Member="DoanhNghieps" ThisKey="MaLoaiGiayPhepKinhDoanh" OtherKey="MaLoaiGiayPhepKinhDoanh" Type="DoanhNghiep" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTaiKhoan" Member="LoaiTaiKhoans">
    <Type Name="LoaiTaiKhoan">
      <Column Name="MaLoaiTaiKhoan" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiTaiKhoan_TaiKhoan" Member="TaiKhoans" ThisKey="MaLoaiTaiKhoan" OtherKey="MaLoaiTaiKhoan" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiThe" Member="LoaiThes">
    <Type Name="LoaiThe">
      <Column Name="MaLoaiThe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiThe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiThe_The" Member="Thes" ThisKey="MaLoaiThe" OtherKey="MaLoaiThe" Type="The" />
    </Type>
  </Table>
  <Table Name="dbo.LogAction" Member="LogActions">
    <Type Name="LogAction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BangLienQuan" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ThaoTac" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DuLieuCu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DuLieuMoi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoiGioiLienKet" Member="MoiGioiLienKets">
    <Type Name="MoiGioiLienKet">
      <Column Name="MaMoiGioiLienKet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenMoiGioiLienKet" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TaiKhoanMoiGioiLienKet" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UrlWebservice" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NgonNgu" Member="NgonNgus">
    <Type Name="NgonNgu">
      <Column Name="MaNgonNgu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BienNgonNgu" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TiengViet" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="TiengAnh" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="LinkTiengAnh" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="LinkTiengViet" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NoiDung" Member="NoiDungs">
    <Type Name="NoiDung">
      <Column Name="MaNoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BienNoiDung" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TiengViet" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TiengAnh" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permissions">
    <Type Name="Permission">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Insert]" Member="Insert" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Update]" Member="Update" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Delete]" Member="Delete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhiGiaoDich" Member="PhiGiaoDiches">
    <Type Name="PhiGiaoDich">
      <Column Name="MaPhiGiaoDich" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiGiaoDich" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Phi" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiGiaoDich_PhiGiaoDich" Member="LoaiGiaoDich" ThisKey="MaLoaiGiaoDich" OtherKey="MaLoaiGiaoDich" Type="LoaiGiaoDich" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SessionID" Member="SessionIDs">
    <Type Name="SessionID">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sID" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="MaTaiKhoan" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoTaiKhoan" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="MaLoaiTaiKhoan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoDu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhauGiaoDich" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TaiKhoan_The" Member="Thes" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="The" />
      <Association Name="TaiKhoan_CaNhan" Member="CaNhans" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="CaNhan" />
      <Association Name="TaiKhoan_DiaChi" Member="DiaChis" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="DiaChi" />
      <Association Name="TaiKhoan_DoanhNghiep" Member="DoanhNghieps" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="DoanhNghiep" />
      <Association Name="LoaiTaiKhoan_TaiKhoan" Member="LoaiTaiKhoan" ThisKey="MaLoaiTaiKhoan" OtherKey="MaLoaiTaiKhoan" Type="LoaiTaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThamSo" Member="ThamSos">
    <Type Name="ThamSo">
      <Column Name="MaThamSo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenThamSo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Kieu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GiaTri" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHoaDon" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaVanChuyen" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongThanhToan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="EmailKhachHangThanhToan" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ChuTaiKhoan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>